/*
 * mdprobe.c — multi-disk virtio-blk probe (OH Phase 1b gap 2).
 *
 * Boots as init on a two-disk QEMU virt (two virtio-blk-pci functions:
 * vda + vdb). Whichever disk is the root, the OTHER one is mounted on
 * /mnt and cross-read, proving both slots carry independent I/O:
 *
 *   - root=/dev/vda run: /marker-a.txt on the root; mounts /dev/vdb,
 *     reads /marker-b.txt + the 512K pattern file, writes + reads back
 *     a small file on vdb.
 *   - root=/dev/vdb run: /marker-b.txt on the root; mounts /dev/vda,
 *     reads /marker-a.txt + the pattern file from vda.
 *
 * Prints one line per check and a final verdict:
 *   MDPROBE RESULT: PASS <n>/<n> | FAIL <p>/<n>
 *
 * Build: see test/multidisk_boot.py (musl static, toolchain/README.md).
 */

#include <errno.h>
#include <fcntl.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/mount.h>
#include <sys/statfs.h>
#include <unistd.h>

#define MARKER_A "RUX-MD-A\n"
#define MARKER_B "RUX-MD-B\n"
#define BIG_BYTES (512 * 1024)

static int total, passed;

static void ok(const char *what)
{
    passed++;
    total++;
    printf("ok   %s\n", what);
}

static void bad(const char *what, long got)
{
    total++;
    printf("FAIL %s (got %ld, errno %d)\n", what, got, errno);
}

#define CHECK_EQ(expr, want, name) \
    do { long _g = (long)(expr); \
         if (_g == (long)(want)) ok(name); \
         else bad(name, _g); } while (0)

static int read_all(const char *path, char *buf, size_t cap, ssize_t *lenp)
{
    int fd = open(path, O_RDONLY);
    if (fd < 0)
        return -1;
    ssize_t n = read(fd, buf, cap - 1);
    close(fd);
    if (n < 0)
        return -1;
    buf[n] = '\0';
    *lenp = n;
    return 0;
}

/* Read the 512K pattern file and verify length + sampled bytes. The
 * pattern is byte i == (i * 7 + 11) & 0xff (generated by the image
 * builder). Exercises many read batches / read-ahead windows on the
 * non-root disk. */
static int check_big_file(const char *dir)
{
    char path[128], buf[4096];
    snprintf(path, sizeof(path), "%s/bigfile.bin", dir);
    int fd = open(path, O_RDONLY);
    if (fd < 0)
        return -1;
    size_t done = 0;
    int bad_byte = 0;
    for (;;) {
        ssize_t n = read(fd, buf, sizeof(buf));
        if (n < 0) {
            close(fd);
            return -1;
        }
        if (n == 0)
            break;
        for (ssize_t i = 0; i < n; i++) {
            uint8_t want = (uint8_t)((done + (size_t)i) * 7 + 11);
            if ((uint8_t)buf[i] != want) {
                bad_byte = 1;
            }
        }
        done += (size_t)n;
    }
    close(fd);
    if (done != BIG_BYTES || bad_byte) {
        printf("FAIL big file on %s (len %zu, bad_byte %d)\n", dir, done,
               bad_byte);
        return -1;
    }
    return 0;
}

int main(void)
{
    char buf[256];
    ssize_t len = 0;
    struct stat st;

    printf("MDPROBE: multi-disk probe start\n");

    /* 1. devtmpfs carries a node for EVERY probed disk. */
    CHECK_EQ(stat("/dev/vda", &st), 0, "stat /dev/vda");
    CHECK_EQ(st.st_mode & S_IFMT, S_IFBLK, "/dev/vda is S_IFBLK");
    CHECK_EQ(stat("/dev/vdb", &st), 0, "stat /dev/vdb");
    CHECK_EQ(st.st_mode & S_IFMT, S_IFBLK, "/dev/vdb is S_IFBLK");

    /* 2. Which disk are we root on? */
    int root_is_a = (access("/marker-a.txt", F_OK) == 0);
    const char *other_dev = root_is_a ? "/dev/vdb" : "/dev/vda";
    const char *other_name = root_is_a ? "vdb" : "vda";
    printf("MDPROBE: root is %s; mounting %s on /mnt\n",
           root_is_a ? "vda" : "vdb", other_dev);

    /* 3. Mount the OTHER disk (separate ext4 instance). */
    CHECK_EQ(mkdir("/mnt", 0755), 0, "mkdir /mnt");
    CHECK_EQ(mount(other_dev, "/mnt", "ext4", 0, NULL), 0,
             "mount other disk on /mnt");

    /* 4. Read its marker. */
    if (read_all("/mnt/marker-a.txt", buf, sizeof(buf), &len) == 0 &&
        strcmp(buf, MARKER_A) == 0) {
        ok("read /mnt/marker-a.txt");
    } else if (read_all("/mnt/marker-b.txt", buf, sizeof(buf), &len) == 0 &&
               strcmp(buf, MARKER_B) == 0) {
        ok("read /mnt/marker-b.txt");
    } else {
        bad("read marker on other disk", -1);
    }

    /* 5. Deep read: 512K pattern across many batches. */
    CHECK_EQ(check_big_file("/mnt"), 0, "big pattern file on other disk");

    /* 6. statfs on the mounted disk (f_type ext2 superblock magic). */
    struct statfs sf;
    CHECK_EQ(statfs("/mnt", &sf), 0, "statfs /mnt");
    CHECK_EQ(sf.f_type, 0xEF53L, "statfs f_type EXT");

    /* 7. Write + read-back on the OTHER disk (write path on the
     * non-root slot; runs under -snapshot so the image is untouched). */
    const char *msg = "rux-md-write\n";
    int fd = open("/mnt/wtest.txt", O_WRONLY | O_CREAT | O_TRUNC, 0644);
    if (fd >= 0) {
        ssize_t w = write(fd, msg, strlen(msg));
        int cs = close(fd);
        CHECK_EQ(w, (ssize_t)strlen(msg), "write /mnt/wtest.txt");
        CHECK_EQ(cs, 0, "close after write");
        if (read_all("/mnt/wtest.txt", buf, sizeof(buf), &len) == 0 &&
            strcmp(buf, msg) == 0 && len == (ssize_t)strlen(msg)) {
            ok("read back /mnt/wtest.txt");
        } else {
            bad("read back /mnt/wtest.txt", -1);
        }
    } else {
        bad("open /mnt/wtest.txt for write", fd);
    }

    /* 8. Root disk still readable after the other disk went live
     * (no clobbering of slot 0 state by slot 1 I/O). */
    if (read_all(root_is_a ? "/marker-a.txt" : "/marker-b.txt", buf,
                 sizeof(buf), &len) == 0 &&
        strcmp(buf, root_is_a ? MARKER_A : MARKER_B) == 0) {
        ok("root marker still readable");
    } else {
        bad("root marker still readable", -1);
    }

    printf("MDPROBE: other disk was %s\n", other_name);
    printf("MDPROBE RESULT: %s %d/%d\n",
           passed == total ? "PASS" : "FAIL", passed, total);
    fflush(stdout);

    for (;;)
        pause();
    return 0;
}
