//! Rux kernel build script
//!
//! This script runs before compilation and is responsible for:
//! 1. Parsing Kernel.toml configuration file
//! 2. Generating configuration code
//! 3. Setting conditional compilation options

use std::env;
use std::fs;
use std::path::PathBuf;
use std::collections::HashMap;

/// Parse build/.config file (simple key=value format)
fn parse_dot_config(content: &str) -> toml::Value {
    // Store configuration for each section
    let mut sections: HashMap<String, HashMap<String, toml::Value>> = HashMap::new();

    for line in content.lines() {
        let line = line.trim();

        // Skip comments and empty lines
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        // Parse section_key=value format
        if let Some(eq_pos) = line.find('=') {
            let key = &line[..eq_pos];
            let value = &line[eq_pos + 1..];
            let value = value.trim();

            // Split section_key (using first underscore as delimiter)
            if let Some(underscore_pos) = key.find('_') {
                let section = &key[..underscore_pos];
                let config_key = &key[underscore_pos + 1..];

                // Convert value type
                let parsed_value = if value == "true" {
                    toml::Value::Boolean(true)
                } else if value == "false" {
                    toml::Value::Boolean(false)
                } else if let Ok(int_val) = value.parse::<i64>() {
                    toml::Value::Integer(int_val)
                } else {
                    toml::Value::String(value.to_string())
                };

                sections.entry(section.to_string())
                    .or_insert_with(HashMap::new)
                    .insert(config_key.to_string(), parsed_value);
            }
        }
    }

    // Build TOML Value
    let mut root_map = toml::map::Map::new();

    // general section
    let mut general = toml::map::Map::new();
    general.insert("name".to_string(), toml::Value::String("Rux".to_string()));
    general.insert("version".to_string(), toml::Value::String("0.1.0".to_string()));
    root_map.insert("general".to_string(), toml::Value::Table(general));

    // platform section
    let mut platform = toml::map::Map::new();
    platform.insert("default_platform".to_string(), toml::Value::String("riscv64".to_string()));
    root_map.insert("platform".to_string(), toml::Value::Table(platform));

    // Other sections - convert HashMap to toml::map::Map
    for (section_name, section_data) in sections {
        let mut toml_map = toml::map::Map::new();
        for (k, v) in section_data {
            toml_map.insert(k, v);
        }
        root_map.insert(section_name, toml::Value::Table(toml_map));
    }

    toml::Value::Table(root_map)
}

fn main() {
    println!("cargo:rerun-if-changed=../Kernel.toml");
    println!("cargo:rerun-if-changed=../build/.config");

    // Try to read build/.config (generated by menuconfig)
    let config_content = if let Ok(content) = fs::read_to_string("../build/.config") {
        println!("cargo:warning=Using build/.config configuration");
        content
    } else {
        // Fall back to Kernel.toml
        fs::read_to_string("../Kernel.toml")
            .expect("Unable to read Kernel.toml")
    };

    // Determine config file type: check for TOML [section] format
    let is_toml = config_content.lines().any(|line| {
        let trimmed = line.trim();
        trimmed.starts_with('[') && trimmed.ends_with(']')
    });

    // Parse configuration
    let config = if is_toml {
        // Parse TOML
        toml::from_str(&config_content)
            .expect("Configuration file parsing failed")
    } else {
        // Parse .config format (generated by menuconfig)
        parse_dot_config(&config_content)
    };

    // Print configuration info
    if let Some(general) = config.get("general") {
        if let Some(name) = general["name"].as_str() {
            println!("cargo:rustc-env=CARGO_KERNEL_NAME={}", name);
        }
        if let Some(version) = general["version"].as_str() {
            println!("cargo:rustc-env=CARGO_KERNEL_VERSION={}", version);
        }
    }

    // Get target platform
    let platform = config.get("platform")
        .and_then(|p| p["default_platform"].as_str())
        .unwrap_or("aarch64");

    println!("cargo:rustc-env=RUX_TARGET_PLATFORM={}", platform);

    // Set Rust compilation options
    if let Some(perf) = config.get("performance") {
        // Set optimization level
        if let Some(opt_level) = perf.get("opt_level").and_then(|v| v.as_integer()) {
            let opt_str = match opt_level {
                0 => "0",
                1 => "1",
                2 => "2",
                3 => "3",
                _ => "2",
            };
            println!("cargo:rustc-env=RUX_OPT_LEVEL={}", opt_str);
        }

        // Set LTO
        if let Some(lto) = perf.get("lto").and_then(|v| v.as_bool()) {
            println!("cargo:rustc-env=RUX_ENABLE_LTO={}", lto);
        }

        // Set codegen-units
        if let Some(units) = perf.get("codegen_units").and_then(|v| v.as_integer()) {
            println!("cargo:rustc-env=RUX_CODEGEN_UNITS={}", units);
        }
    }

    // Set feature flags
    if let Some(platform) = config.get("platform") {
        let enable_aarch64 = platform.get("enable_aarch64")
            .and_then(|v| v.as_bool())
            .unwrap_or(false);

        let enable_x86_64 = platform.get("enable_x86_64")
            .and_then(|v| v.as_bool())
            .unwrap_or(false);

        let enable_riscv64 = platform.get("enable_riscv64")
            .and_then(|v| v.as_bool())
            .unwrap_or(false);

        // Output enabled platforms
        let enabled_platforms = [
            if enable_aarch64 { "aarch64" } else { "" },
            if enable_x86_64 { "x86_64" } else { "" },
            if enable_riscv64 { "riscv64" } else { "" },
        ];
        println!("cargo:rustc-env=RUX_ENABLED_PLATFORMS={}", enabled_platforms.join(","));
    }

    // Set debug options
    if let Some(debug) = config.get("debug") {
        if let Some(log_level) = debug.get("log_level").and_then(|v| v.as_str()) {
            println!("cargo:rustc-env=RUX_LOG_LEVEL={}", log_level);
        }

        if debug.get("debug_output").and_then(|v| v.as_bool()).unwrap_or(false) {
            println!("cargo:rustc-env=RUX_DEBUG={}", "true");
        }

        if debug.get("profiling").and_then(|v| v.as_bool()).unwrap_or(false) {
            println!("cargo:rustc-env=RUX_PROFILING={}", "true");
        }
    }

    // Generate configuration code
    generate_config_code(&config);

    println!("cargo:warning=Rux configuration loaded successfully");
}

fn generate_config_code(config: &toml::Value) {
    let _out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());

    // Get basic information
    let kernel_name = config.get("general")
        .and_then(|g| g["name"].as_str())
        .unwrap_or("Rux");

    let kernel_version = config.get("general")
        .and_then(|g| g["version"].as_str())
        .unwrap_or("0.1.0");

    let target_platform = config.get("platform")
        .and_then(|p| p["default_platform"].as_str())
        .unwrap_or("aarch64");

    // Generate configuration code
    let config_header = format!(
        r#"//! Rux kernel configuration (auto-generated)
//!
//! This file is auto-generated by build.rs from Kernel.toml, do not edit manually

// ============================================================
// Basic Information
// ============================================================

/// Kernel name
pub const KERNEL_NAME: &str = "{}";

/// Kernel version
pub const KERNEL_VERSION: &str = "{}";

/// Target platform
pub const TARGET_PLATFORM: &str = "{}";

// ============================================================
// Memory Configuration
// ============================================================

/// Kernel heap size (bytes)
pub const KERNEL_HEAP_SIZE: usize = {};

/// Physical memory size (bytes)
pub const PHYS_MEMORY_SIZE: usize = {};

/// Page size
pub const PAGE_SIZE: usize = {};

/// Page size shift
pub const PAGE_SHIFT: usize = {};

// ============================================================
// Driver Configuration
// ============================================================

/// Enable UART driver
pub const ENABLE_UART: bool = {};

/// Enable timer driver
pub const ENABLE_TIMER: bool = {};

/// Enable GIC interrupt controller
pub const ENABLE_GIC: bool = {};

/// Enable VirtIO network device probing
pub const ENABLE_VIRTIO_NET_PROBE: bool = {};

// ============================================================
// SMP Configuration
// ============================================================

/// Enable SMP multi-core support
pub const ENABLE_SMP: bool = {};

/// Maximum number of CPUs
pub const MAX_CPUS: usize = {};

// ============================================================
// Scheduler Configuration
// ============================================================

/// Enable scheduler
pub const ENABLE_SCHEDULER: bool = {};

/// Default time slice (milliseconds)
pub const DEFAULT_TIME_SLICE_MS: u32 = {};

/// Time slice ticks
pub const TIME_SLICE_TICKS: u32 = {};

// ============================================================
// Memory Management Configuration
// ============================================================

/// User stack size (bytes)
pub const USER_STACK_SIZE: usize = {};

/// User stack top address
pub const USER_STACK_TOP: u64 = {};

/// Maximum number of page tables
pub const MAX_PAGE_TABLES: usize = {};

// ============================================================
// Network Configuration
// ============================================================

/// Enable network stack
pub const ENABLE_NETWORK: bool = {};

/// Ethernet MTU
pub const ETH_MTU: usize = {};

/// TCP socket table size
pub const TCP_SOCKET_TABLE_SIZE: usize = {};

/// UDP socket table size
pub const UDP_SOCKET_TABLE_SIZE: usize = {};

/// ARP cache size
pub const ARP_CACHE_SIZE: usize = {};

/// Route table size
pub const ROUTE_TABLE_SIZE: usize = {};

/// IPv4 default TTL
pub const IP_DEFAULT_TTL: u8 = {};

// ============================================================
// Feature Flags
// ============================================================

/// Enable TCP protocol
pub const ENABLE_TCP: bool = {};

/// Enable UDP protocol
pub const ENABLE_UDP: bool = {};

/// Enable ARP protocol
pub const ENABLE_ARP: bool = {};

/// Enable IPv4 protocol
pub const ENABLE_IPV4: bool = {};

/// Enable Ethernet
pub const ENABLE_ETHERNET: bool = {};

/// Enable signal handling
pub const ENABLE_SIGNAL: bool = {};

/// Enable virtual memory
pub const ENABLE_VM: bool = {};

/// Enable VFS
pub const ENABLE_VFS: bool = {};

/// Enable pipe
pub const ENABLE_PIPE: bool = {};

// ============================================================
// Mount Configuration
// ============================================================

/// ext4 disk mount point
pub const EXT4_MOUNT_POINT: &str = "{}";

/// Enable ext4 auto-mount
pub const AUTO_MOUNT_EXT4: bool = {};

/// Enable procfs auto-mount
pub const AUTO_MOUNT_PROCFS: bool = {};
"#,
        kernel_name,
        kernel_version,
        target_platform,
        config.get("memory")
            .and_then(|m| m.get("kernel_heap_size"))
            .and_then(|v| v.as_integer())
            .unwrap_or(16) * 1024 * 1024,
        config.get("memory")
            .and_then(|m| m.get("physical_memory"))
            .and_then(|v| v.as_integer())
            .unwrap_or(2048) * 1024 * 1024,
        config.get("memory")
            .and_then(|m| m.get("page_size"))
            .and_then(|v| v.as_integer())
            .unwrap_or(4096),
        config.get("memory")
            .and_then(|m| m.get("page_size"))
            .and_then(|v| v.as_integer())
            .unwrap_or(4096)
            .trailing_zeros() as usize,
        config.get("drivers")
            .and_then(|d| d.get("enable_uart"))
            .and_then(|v| v.as_bool())
            .unwrap_or(true),
        config.get("drivers")
            .and_then(|d| d.get("enable_timer"))
            .and_then(|v| v.as_bool())
            .unwrap_or(true),
        config.get("drivers")
            .and_then(|d| d.get("enable_gic"))
            .and_then(|v| v.as_bool())
            .unwrap_or(false),
        config.get("drivers")
            .and_then(|d| d.get("enable_virtio_net_probe"))
            .and_then(|v| v.as_bool())
            .unwrap_or(false),
        // SMP configuration
        config.get("smp")
            .and_then(|s| s.get("enable_smp"))
            .and_then(|v| v.as_bool())
            .unwrap_or(true),
        config.get("smp")
            .and_then(|s| s.get("max_cpus"))
            .and_then(|v| v.as_integer())
            .unwrap_or(4) as usize,
        // Scheduler configuration
        config.get("scheduler")
            .and_then(|s| s.get("enable_scheduler"))
            .and_then(|v| v.as_bool())
            .unwrap_or(true),
        config.get("scheduler")
            .and_then(|s| s.get("default_time_slice_ms"))
            .and_then(|v| v.as_integer())
            .unwrap_or(100) as u32,
        config.get("scheduler")
            .and_then(|s| s.get("time_slice_ticks"))
            .and_then(|v| v.as_integer())
            .unwrap_or(10) as u32,
        // Memory management configuration
        config.get("memory")
            .and_then(|m| m.get("user_stack_size"))
            .and_then(|v| v.as_integer())
            .unwrap_or(8) * 1024 * 1024,
        0x0000_003f_ffff_f000u64,
        config.get("memory")
            .and_then(|m| m.get("max_page_tables"))
            .and_then(|v| v.as_integer())
            .unwrap_or(256) as usize,
        // Network configuration
        config.get("network")
            .and_then(|n| n.get("enable_network"))
            .and_then(|v| v.as_bool())
            .unwrap_or(true),
        config.get("network")
            .and_then(|n| n.get("eth_mtu"))
            .and_then(|v| v.as_integer())
            .unwrap_or(1500) as usize,
        config.get("network")
            .and_then(|n| n.get("tcp_socket_table_size"))
            .and_then(|v| v.as_integer())
            .unwrap_or(64) as usize,
        config.get("network")
            .and_then(|n| n.get("udp_socket_table_size"))
            .and_then(|v| v.as_integer())
            .unwrap_or(64) as usize,
        config.get("network")
            .and_then(|n| n.get("arp_cache_size"))
            .and_then(|v| v.as_integer())
            .unwrap_or(64) as usize,
        config.get("network")
            .and_then(|n| n.get("route_table_size"))
            .and_then(|v| v.as_integer())
            .unwrap_or(64) as usize,
        config.get("network")
            .and_then(|n| n.get("ip_default_ttl"))
            .and_then(|v| v.as_integer())
            .unwrap_or(64) as u8,
        // Feature flags
        config.get("features")
            .and_then(|f| f.get("enable_tcp"))
            .and_then(|v| v.as_bool())
            .unwrap_or(true),
        config.get("features")
            .and_then(|f| f.get("enable_udp"))
            .and_then(|v| v.as_bool())
            .unwrap_or(true),
        config.get("features")
            .and_then(|f| f.get("enable_arp"))
            .and_then(|v| v.as_bool())
            .unwrap_or(true),
        config.get("features")
            .and_then(|f| f.get("enable_ipv4"))
            .and_then(|v| v.as_bool())
            .unwrap_or(true),
        config.get("features")
            .and_then(|f| f.get("enable_ethernet"))
            .and_then(|v| v.as_bool())
            .unwrap_or(true),
        config.get("features")
            .and_then(|f| f.get("enable_signal"))
            .and_then(|v| v.as_bool())
            .unwrap_or(true),
        config.get("features")
            .and_then(|f| f.get("enable_vm"))
            .and_then(|v| v.as_bool())
            .unwrap_or(true),
        config.get("features")
            .and_then(|f| f.get("enable_vfs"))
            .and_then(|v| v.as_bool())
            .unwrap_or(true),
        config.get("features")
            .and_then(|f| f.get("enable_pipe"))
            .and_then(|v| v.as_bool())
            .unwrap_or(true),
        // Mount configuration
        config.get("mount")
            .and_then(|m| m.get("ext4_mount_point"))
            .and_then(|v| v.as_str())
            .unwrap_or("/"),
        config.get("mount")
            .and_then(|m| m.get("auto_mount_ext4"))
            .and_then(|v| v.as_bool())
            .unwrap_or(true),
        config.get("mount")
            .and_then(|m| m.get("auto_mount_procfs"))
            .and_then(|v| v.as_bool())
            .unwrap_or(true),
    );

    let src_dir = manifest_dir.join("src");
    let config_file = src_dir.join("config.rs");

    // Only write when content changes, to avoid updating file timestamp on every build
    let existing_content = fs::read_to_string(&config_file).unwrap_or_default();
    if existing_content != config_header {
        fs::write(&config_file, &config_header)
            .expect("Failed to write configuration file");
    }
}
