//! Rux kernel build script
//!
//! This script runs before compilation and is responsible for:
//! 1. Parsing Kernel.toml configuration file
//! 2. Generating configuration code
//! 3. Setting conditional compilation options

use std::env;
use std::fs;
use std::path::PathBuf;
use std::collections::HashMap;

/// Parse build/.config file (simple key=value format)
fn parse_dot_config(content: &str) -> toml::Value {
    // Store configuration for each section
    let mut sections: HashMap<String, HashMap<String, toml::Value>> = HashMap::new();

    for line in content.lines() {
        let line = line.trim();

        // Skip comments and empty lines
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        // Parse section_key=value format
        if let Some(eq_pos) = line.find('=') {
            let key = &line[..eq_pos];
            let value = &line[eq_pos + 1..];
            let value = value.trim();

            // Split section_key (using first underscore as delimiter)
            if let Some(underscore_pos) = key.find('_') {
                let section = &key[..underscore_pos];
                let config_key = &key[underscore_pos + 1..];

                // Convert value type
                let parsed_value = if value == "true" {
                    toml::Value::Boolean(true)
                } else if value == "false" {
                    toml::Value::Boolean(false)
                } else if let Ok(int_val) = value.parse::<i64>() {
                    toml::Value::Integer(int_val)
                } else {
                    toml::Value::String(value.to_string())
                };

                sections.entry(section.to_string())
                    .or_insert_with(HashMap::new)
                    .insert(config_key.to_string(), parsed_value);
            }
        }
    }

    // Build TOML Value
    let mut root_map = toml::map::Map::new();

    // general section
    let mut general = toml::map::Map::new();
    general.insert("name".to_string(), toml::Value::String("Rux".to_string()));
    general.insert("version".to_string(), toml::Value::String("0.1.0".to_string()));
    root_map.insert("general".to_string(), toml::Value::Table(general));

    // platform section
    let mut platform = toml::map::Map::new();
    platform.insert("default_platform".to_string(), toml::Value::String("riscv64".to_string()));
    root_map.insert("platform".to_string(), toml::Value::Table(platform));

    // Other sections - convert HashMap to toml::map::Map
    for (section_name, section_data) in sections {
        let mut toml_map = toml::map::Map::new();
        for (k, v) in section_data {
            toml_map.insert(k, v);
        }
        root_map.insert(section_name, toml::Value::Table(toml_map));
    }

    toml::Value::Table(root_map)
}

fn main() {
    println!("cargo:rerun-if-changed=../Kernel.toml");
    println!("cargo:rerun-if-changed=../build/.config");

    // Set build time and rustc version
    let build_time = chrono::Local::now().format("%Y-%m-%d %H:%M:%S %Z").to_string();
    println!("cargo:rustc-env=BUILD_TIME={}", build_time);

    // Get rustc version
    let rustc_version = rustc_version::version()
        .map(|v| v.to_string())
        .unwrap_or_else(|_| "unknown".to_string());
    println!("cargo:rustc-env=RUSTC_VERSION={}", rustc_version);

    // Try to read build/.config (generated by menuconfig)
    let config_content = if let Ok(content) = fs::read_to_string("../build/.config") {
        println!("cargo:warning=Using build/.config configuration");
        content
    } else {
        // Fall back to Kernel.toml
        fs::read_to_string("../Kernel.toml")
            .expect("Unable to read Kernel.toml")
    };

    // Determine config file type: check for TOML [section] format
    let is_toml = config_content.lines().any(|line| {
        let trimmed = line.trim();
        trimmed.starts_with('[') && trimmed.ends_with(']')
    });

    // Parse configuration
    let config = if is_toml {
        // Parse TOML
        toml::from_str(&config_content)
            .expect("Configuration file parsing failed")
    } else {
        // Parse .config format (generated by menuconfig)
        parse_dot_config(&config_content)
    };

    // Print configuration info
    if let Some(general) = config.get("general") {
        if let Some(name) = general["name"].as_str() {
            println!("cargo:rustc-env=CARGO_KERNEL_NAME={}", name);
        }
        if let Some(version) = general["version"].as_str() {
            println!("cargo:rustc-env=CARGO_KERNEL_VERSION={}", version);
        }
    }

    // Get target platform
    let platform = config.get("platform")
        .and_then(|p| p["default_platform"].as_str())
        .unwrap_or("aarch64");

    println!("cargo:rustc-env=RUX_TARGET_PLATFORM={}", platform);

    // Set Rust compilation options
    if let Some(perf) = config.get("performance") {
        // Set optimization level
        if let Some(opt_level) = perf.get("opt_level").and_then(|v| v.as_integer()) {
            let opt_str = match opt_level {
                0 => "0",
                1 => "1",
                2 => "2",
                3 => "3",
                _ => "2",
            };
            println!("cargo:rustc-env=RUX_OPT_LEVEL={}", opt_str);
        }

        // Set LTO
        if let Some(lto) = perf.get("lto").and_then(|v| v.as_bool()) {
            println!("cargo:rustc-env=RUX_ENABLE_LTO={}", lto);
        }

        // Set codegen-units
        if let Some(units) = perf.get("codegen_units").and_then(|v| v.as_integer()) {
            println!("cargo:rustc-env=RUX_CODEGEN_UNITS={}", units);
        }
    }

    // Set feature flags
    if let Some(platform) = config.get("platform") {
        let enable_aarch64 = platform.get("enable_aarch64")
            .and_then(|v| v.as_bool())
            .unwrap_or(false);

        let enable_x86_64 = platform.get("enable_x86_64")
            .and_then(|v| v.as_bool())
            .unwrap_or(false);

        let enable_riscv64 = platform.get("enable_riscv64")
            .and_then(|v| v.as_bool())
            .unwrap_or(false);

        // Output enabled platforms
        let enabled_platforms = [
            if enable_aarch64 { "aarch64" } else { "" },
            if enable_x86_64 { "x86_64" } else { "" },
            if enable_riscv64 { "riscv64" } else { "" },
        ];
        println!("cargo:rustc-env=RUX_ENABLED_PLATFORMS={}", enabled_platforms.join(","));
    }

    // Set debug options
    if let Some(debug) = config.get("debug") {
        if let Some(log_level) = debug.get("log_level").and_then(|v| v.as_str()) {
            println!("cargo:rustc-env=RUX_LOG_LEVEL={}", log_level);
        }

        if debug.get("debug_output").and_then(|v| v.as_bool()).unwrap_or(false) {
            println!("cargo:rustc-env=RUX_DEBUG={}", "true");
        }

        if debug.get("profiling").and_then(|v| v.as_bool()).unwrap_or(false) {
            println!("cargo:rustc-env=RUX_PROFILING={}", "true");
        }
    }

    // Generate configuration code
    generate_config_code(&config);

    println!("cargo:warning=Rux configuration loaded successfully");
}

fn generate_config_code(config: &toml::Value) {
    let _out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());

    // Get basic information
    let kernel_name = config.get("general")
        .and_then(|g| g["name"].as_str())
        .unwrap_or("Rux");

    let kernel_version = config.get("general")
        .and_then(|g| g["version"].as_str())
        .unwrap_or("0.1.0");

    let target_platform = config.get("platform")
        .and_then(|p| p["default_platform"].as_str())
        .unwrap_or("aarch64");

    // Helper functions to get config values with defaults
    let get_usize = |section: &str, key: &str, default: i64| -> usize {
        config.get(section)
            .and_then(|s| s.get(key))
            .and_then(|v| v.as_integer())
            .unwrap_or(default) as usize
    };

    let get_u32 = |section: &str, key: &str, default: i64| -> u32 {
        config.get(section)
            .and_then(|s| s.get(key))
            .and_then(|v| v.as_integer())
            .unwrap_or(default) as u32
    };

    let get_u64 = |section: &str, key: &str, default: i64| -> u64 {
        config.get(section)
            .and_then(|s| s.get(key))
            .and_then(|v| v.as_integer())
            .unwrap_or(default) as u64
    };

    let get_u8 = |section: &str, key: &str, default: i64| -> u8 {
        config.get(section)
            .and_then(|s| s.get(key))
            .and_then(|v| v.as_integer())
            .unwrap_or(default) as u8
    };

    let get_bool = |section: &str, key: &str, default: bool| -> bool {
        config.get(section)
            .and_then(|s| s.get(key))
            .and_then(|v| v.as_bool())
            .unwrap_or(default)
    };

    let get_str = |section: &str, key: &str, default: &str| -> String {
        config.get(section)
            .and_then(|s| s.get(key))
            .and_then(|v| v.as_str())
            .unwrap_or(default)
            .to_string()
    };

    // Generate configuration code
    let config_header = format!(
        r#"//! Rux kernel configuration (auto-generated)
//!
//! This file is auto-generated by build.rs from Kernel.toml, do not edit manually

// ============================================================
// Basic Information
// ============================================================

/// Kernel name
pub const KERNEL_NAME: &str = "{}";

/// Kernel version
pub const KERNEL_VERSION: &str = "{}";

/// Target platform
pub const TARGET_PLATFORM: &str = "{}";

// ============================================================
// Memory Configuration
// ============================================================

/// Kernel heap size (bytes)
pub const KERNEL_HEAP_SIZE: usize = {};

/// Physical memory size (bytes)
pub const PHYS_MEMORY_SIZE: usize = {};

/// Page size
pub const PAGE_SIZE: usize = {};

/// Page size shift
pub const PAGE_SHIFT: usize = {};

/// User stack size (bytes)
pub const USER_STACK_SIZE: usize = {};

/// User stack max size (bytes)
pub const USER_STACK_MAX_SIZE: usize = {};

/// User heap max size (bytes)
pub const USER_HEAP_MAX_SIZE: usize = {};

/// Kernel stack size (bytes)
pub const KERNEL_STACK_SIZE: usize = {};

/// User stack top address
pub const USER_STACK_TOP: u64 = 0x0000_003f_ffff_f000;

/// Maximum number of page tables
pub const MAX_PAGE_TABLES: usize = {};

/// Buddy allocator max order
pub const BUDDY_MAX_ORDER: usize = {};

/// Slab cache count
pub const SLAB_NUM_CACHES: usize = {};

/// Per-CPU page cache high watermark
pub const PCP_HIGH: usize = {};

/// Per-CPU page cache low watermark
pub const PCP_LOW: usize = {};

/// Per-CPU page cache batch size
pub const PCP_BATCH: usize = {};

// ============================================================
// Driver Configuration
// ============================================================

/// Enable UART driver
pub const ENABLE_UART: bool = {};

/// Enable timer driver
pub const ENABLE_TIMER: bool = {};

/// Enable GIC interrupt controller
pub const ENABLE_GIC: bool = {};

/// Enable VirtIO network device probing
pub const ENABLE_VIRTIO_NET_PROBE: bool = {};

/// Maximum VirtIO devices
pub const VIRTIO_MAX_DEVICES: usize = {};

/// VirtIO queue wait timeout (microseconds)
pub const VIRTIO_QUEUE_TIMEOUT_US: u64 = {};

/// VirtIO device reset timeout (ticks)
pub const VIRTIO_RESET_TIMEOUT_TICKS: usize = {};

/// VirtIO PCI max capabilities
pub const VIRTIO_PCI_MAX_CAPABILITIES: usize = {};

/// Maximum PLIC interrupts
pub const PLIC_MAX_INTERRUPTS: usize = {};

/// Event device queue size
pub const EVDEV_EVENT_QUEUE_SIZE: usize = {};

/// Timer clock frequency (Hz)
pub const TIMER_CLOCK_FREQ_HZ: u64 = {};

// ============================================================
// SMP Configuration
// ============================================================

/// Enable SMP multi-core support
pub const ENABLE_SMP: bool = {};

/// Maximum number of CPUs
pub const MAX_CPUS: usize = {};

/// SMP boot stack size (bytes)
pub const SMP_BOOT_STACK_SIZE: usize = {};

// ============================================================
// Scheduler Configuration
// ============================================================

/// Enable scheduler
pub const ENABLE_SCHEDULER: bool = {};

/// Default time slice (milliseconds)
pub const DEFAULT_TIME_SLICE_MS: u32 = {};

/// Time slice ticks
pub const TIME_SLICE_TICKS: u32 = {};

/// Maximum number of tasks
pub const MAX_TASKS: usize = {};

/// Task pool size for per-CPU allocation
pub const TASK_POOL_SIZE: usize = {};

/// Load imbalance threshold for SMP balancing
pub const LOAD_IMBALANCE_THRESH: usize = {};

/// CFS minimum granularity (nanoseconds)
pub const CFS_MIN_GRANULARITY_NS: u64 = {};

/// CFS scheduling latency (nanoseconds)
pub const CFS_LATENCY_NS: u64 = {};

/// Kernel HZ (timer interrupts per second)
pub const KERNEL_HZ: u32 = {};

// ============================================================
// Network Configuration
// ============================================================

/// Enable network stack
pub const ENABLE_NETWORK: bool = {};

/// Ethernet MTU
pub const ETH_MTU: usize = {};

/// TCP socket table size
pub const TCP_SOCKET_TABLE_SIZE: usize = {};

/// UDP socket table size
pub const UDP_SOCKET_TABLE_SIZE: usize = {};

/// ARP cache size
pub const ARP_CACHE_SIZE: usize = {};

/// Route table size
pub const ROUTE_TABLE_SIZE: usize = {};

/// IPv4 default TTL
pub const IP_DEFAULT_TTL: u8 = {};

/// TCP minimum RTO (microseconds)
pub const TCP_RTO_MIN_US: u64 = {};

/// TCP maximum RTO (microseconds)
pub const TCP_RTO_MAX_US: u64 = {};

/// TCP default RTO (microseconds)
pub const TCP_RTO_DEFAULT_US: u64 = {};

/// TCP maximum retransmit count
pub const TCP_MAX_RETRIES: u32 = {};

/// TCP delayed ACK timeout (microseconds)
pub const TCP_DELACK_TIMEOUT_US: u64 = {};

/// TCP TIME_WAIT timeout (microseconds)
pub const TCP_TIMEWAIT_TIMEOUT_US: u64 = {};

// ============================================================
// Feature Flags
// ============================================================

/// Enable TCP protocol
pub const ENABLE_TCP: bool = {};

/// Enable UDP protocol
pub const ENABLE_UDP: bool = {};

/// Enable ARP protocol
pub const ENABLE_ARP: bool = {};

/// Enable IPv4 protocol
pub const ENABLE_IPV4: bool = {};

/// Enable Ethernet
pub const ENABLE_ETHERNET: bool = {};

/// Enable signal handling
pub const ENABLE_SIGNAL: bool = {};

/// Enable virtual memory
pub const ENABLE_VM: bool = {};

/// Enable VFS
pub const ENABLE_VFS: bool = {};

/// Enable pipe
pub const ENABLE_PIPE: bool = {};

// ============================================================
// Mount Configuration
// ============================================================

/// ext4 disk mount point
pub const EXT4_MOUNT_POINT: &str = "{}";

/// Enable ext4 auto-mount
pub const AUTO_MOUNT_EXT4: bool = {};

/// Enable procfs auto-mount
pub const AUTO_MOUNT_PROCFS: bool = {};

// ============================================================
// Filesystem Configuration
// ============================================================

/// Pipe buffer size (bytes)
pub const PIPE_BUFFER_SIZE: usize = {};

/// Inode cache size
pub const ICACHE_SIZE: usize = {};

/// Directory entry cache size
pub const DCACHE_SIZE: usize = {};

/// Rootfs path cache size
pub const ROOTFS_PATH_CACHE_SIZE: usize = {};

/// Maximum symlink follow depth
pub const MAX_SYMLINKS: usize = {};

/// Maximum symlink depth in ext4
pub const EXT4_MAX_SYMLINK_DEPTH: usize = {};

// ============================================================
// Process Configuration
// ============================================================

/// Maximum PID value
pub const PID_MAX_LIMIT: usize = {};

/// Maximum command line length
pub const MAX_CMDLINE_LEN: usize = {};

/// File descriptor set size for select
pub const FD_SETSIZE: usize = {};

// ============================================================
// Synchronization Configuration
// ============================================================

/// Futex waiter pool size
pub const FUTEX_WAITER_POOL_SIZE: usize = {};

/// Futex hash table size
pub const FUTEX_HASH_SIZE: usize = {};

// ============================================================
// Graphics Configuration
// ============================================================

/// Default framebuffer width
pub const FB_DEFAULT_WIDTH: usize = {};

/// Default framebuffer height
pub const FB_DEFAULT_HEIGHT: usize = {};
"#,
        kernel_name,
        kernel_version,
        target_platform,
        // Memory
        get_usize("memory", "kernel_heap_size", 16) * 1024 * 1024,
        get_usize("memory", "physical_memory", 2048) * 1024 * 1024,
        get_usize("memory", "page_size", 4096),
        get_usize("memory", "page_size", 4096).trailing_zeros() as usize,
        get_usize("memory", "user_stack_size", 8) * 1024 * 1024,
        get_usize("memory", "user_stack_max_size", 8388608),
        get_usize("memory", "user_heap_max_size", 134217728),
        get_usize("memory", "kernel_stack_size", 32768),
        get_usize("memory", "max_page_tables", 1024),
        get_usize("memory", "buddy_max_order", 20),
        get_usize("memory", "slab_num_caches", 10),
        get_usize("memory", "pcp_high", 64),
        get_usize("memory", "pcp_low", 16),
        get_usize("memory", "pcp_batch", 16),
        // Drivers
        get_bool("drivers", "enable_uart", true),
        get_bool("drivers", "enable_timer", true),
        get_bool("drivers", "enable_gic", false),
        get_bool("drivers", "enable_virtio_net_probe", true),
        get_usize("drivers", "virtio_max_devices", 8),
        get_u64("drivers", "virtio_queue_timeout_us", 10000000),
        get_usize("drivers", "virtio_reset_timeout_ticks", 100000),
        get_usize("drivers", "virtio_pci_max_capabilities", 48),
        get_usize("drivers", "plic_max_interrupts", 128),
        get_usize("drivers", "evdev_event_queue_size", 64),
        get_u64("drivers", "timer_clock_freq_hz", 10000000),
        // SMP
        get_bool("smp", "enable_smp", true),
        get_usize("smp", "max_cpus", 4),
        get_usize("smp", "boot_stack_size", 65536),
        // Scheduler
        get_bool("scheduler", "enable_scheduler", true),
        get_u32("scheduler", "default_time_slice_ms", 100),
        get_u32("scheduler", "time_slice_ticks", 10),
        get_usize("scheduler", "max_tasks", 256),
        get_usize("scheduler", "task_pool_size", 16),
        get_usize("scheduler", "load_imbalance_thresh", 2),
        get_u64("scheduler", "cfs_min_granularity_ns", 700000),
        get_u64("scheduler", "cfs_latency_ns", 6000000),
        get_u32("scheduler", "kernel_hz", 100),
        // Network
        get_bool("network", "enable_network", true),
        get_usize("network", "eth_mtu", 1500),
        get_usize("network", "tcp_socket_table_size", 64),
        get_usize("network", "udp_socket_table_size", 64),
        get_usize("network", "arp_cache_size", 64),
        get_usize("network", "route_table_size", 64),
        get_u8("network", "ip_default_ttl", 64),
        get_u64("network", "tcp_rto_min_us", 200000),
        get_u64("network", "tcp_rto_max_us", 120000000),
        get_u64("network", "tcp_rto_default_us", 1000000),
        get_u32("network", "tcp_max_retries", 15),
        get_u64("network", "tcp_delack_timeout_us", 40000),
        get_u64("network", "tcp_timewait_timeout_us", 60000000),
        // Features
        get_bool("features", "enable_tcp", true),
        get_bool("features", "enable_udp", true),
        get_bool("features", "enable_arp", true),
        get_bool("features", "enable_ipv4", true),
        get_bool("features", "enable_ethernet", true),
        get_bool("features", "enable_signal", true),
        get_bool("features", "enable_vm", true),
        get_bool("features", "enable_vfs", true),
        get_bool("features", "enable_pipe", true),
        // Mount
        get_str("mount", "ext4_mount_point", "/").as_str(),
        get_bool("mount", "auto_mount_ext4", true),
        get_bool("mount", "auto_mount_procfs", true),
        // Filesystem
        get_usize("filesystem", "pipe_buffer_size", 16384),
        get_usize("filesystem", "icache_size", 256),
        get_usize("filesystem", "dcache_size", 256),
        get_usize("filesystem", "rootfs_path_cache_size", 64),
        get_usize("filesystem", "max_symlinks", 40),
        get_usize("filesystem", "ext4_max_symlink_depth", 8),
        // Process
        get_usize("process", "pid_max_limit", 4194304),
        get_usize("process", "max_cmdline_len", 2048),
        get_usize("process", "fd_setsize", 64),
        // Sync
        get_usize("sync", "futex_waiter_pool_size", 256),
        get_usize("sync", "futex_hash_size", 64),
        // Graphics
        get_usize("graphics", "fb_default_width", 1024),
        get_usize("graphics", "fb_default_height", 768),
    );

    let src_dir = manifest_dir.join("src");
    let config_file = src_dir.join("config.rs");

    // Only write when content changes, to avoid updating file timestamp on every build
    let existing_content = fs::read_to_string(&config_file).unwrap_or_default();
    if existing_content != config_header {
        fs::write(&config_file, &config_header)
            .expect("Failed to write configuration file");
    }
}
