//! Rux kernel configuration (auto-generated)
//!
//! This file is auto-generated by build.rs from Kernel.toml, do not edit manually

// ============================================================
// Basic Information
// ============================================================

/// Kernel name
pub const KERNEL_NAME: &str = "Rux";

/// Kernel version
pub const KERNEL_VERSION: &str = "0.1.0";

/// Target platform
pub const TARGET_PLATFORM: &str = "riscv64";

// ============================================================
// Memory Configuration
// ============================================================

/// Kernel heap size (bytes)
pub const KERNEL_HEAP_SIZE: usize = 33554432;

/// Physical memory size (bytes)
pub const PHYS_MEMORY_SIZE: usize = 2147483648;

/// Page size
pub const PAGE_SIZE: usize = 4096;

/// Page size shift
pub const PAGE_SHIFT: usize = 12;

// ============================================================
// Driver Configuration
// ============================================================

/// Enable UART driver
pub const ENABLE_UART: bool = true;

/// Enable timer driver
pub const ENABLE_TIMER: bool = true;

/// Enable GIC interrupt controller
pub const ENABLE_GIC: bool = false;

/// Enable VirtIO network device probing
pub const ENABLE_VIRTIO_NET_PROBE: bool = true;

// ============================================================
// SMP Configuration
// ============================================================

/// Enable SMP multi-core support
pub const ENABLE_SMP: bool = true;

/// Maximum number of CPUs
pub const MAX_CPUS: usize = 4;

// ============================================================
// Scheduler Configuration
// ============================================================

/// Enable scheduler
pub const ENABLE_SCHEDULER: bool = true;

/// Default time slice (milliseconds)
pub const DEFAULT_TIME_SLICE_MS: u32 = 100;

/// Time slice ticks
pub const TIME_SLICE_TICKS: u32 = 10;

// ============================================================
// Memory Management Configuration
// ============================================================

/// User stack size (bytes)
pub const USER_STACK_SIZE: usize = 8388608;

/// User stack top address
pub const USER_STACK_TOP: u64 = 274877902848;

/// Maximum number of page tables
pub const MAX_PAGE_TABLES: usize = 1024;

// ============================================================
// Network Configuration
// ============================================================

/// Enable network stack
pub const ENABLE_NETWORK: bool = true;

/// Ethernet MTU
pub const ETH_MTU: usize = 1500;

/// TCP socket table size
pub const TCP_SOCKET_TABLE_SIZE: usize = 64;

/// UDP socket table size
pub const UDP_SOCKET_TABLE_SIZE: usize = 64;

/// ARP cache size
pub const ARP_CACHE_SIZE: usize = 64;

/// Route table size
pub const ROUTE_TABLE_SIZE: usize = 64;

/// IPv4 default TTL
pub const IP_DEFAULT_TTL: u8 = 64;

// ============================================================
// Feature Flags
// ============================================================

/// Enable TCP protocol
pub const ENABLE_TCP: bool = true;

/// Enable UDP protocol
pub const ENABLE_UDP: bool = true;

/// Enable ARP protocol
pub const ENABLE_ARP: bool = true;

/// Enable IPv4 protocol
pub const ENABLE_IPV4: bool = true;

/// Enable Ethernet
pub const ENABLE_ETHERNET: bool = true;

/// Enable signal handling
pub const ENABLE_SIGNAL: bool = true;

/// Enable virtual memory
pub const ENABLE_VM: bool = true;

/// Enable VFS
pub const ENABLE_VFS: bool = true;

/// Enable pipe
pub const ENABLE_PIPE: bool = true;

// ============================================================
// Mount Configuration
// ============================================================

/// ext4 disk mount point
pub const EXT4_MOUNT_POINT: &str = "/";

/// Enable ext4 auto-mount
pub const AUTO_MOUNT_EXT4: bool = true;

/// Enable procfs auto-mount
pub const AUTO_MOUNT_PROCFS: bool = true;
